/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import admin.*;
import config.session;
import crud.changepassword;
import crud.editaccount;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import panel.login;

/**
 *
 * @author vienz
 */
public class account extends javax.swing.JFrame {

    /**
     * Creates new form account
     */
    public account() {
        initComponents();
        accountInformation();
        
    }
    public void accountInformation() {

        session sess = session.getInstance();

        String fullName = session.getFirstName() + " " + session.getLastName();

        name.setText("Name: " + fullName);
        

        email.setText("Email: " +session.getEmail());
        
        
        cnum.setText("Contact Number: " +session.getContact());
        
        role.setText("Role: " + session.getAcc_type());
     

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        profilepic = new javax.swing.JLabel();
        cnum = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        changeProfileButton = new javax.swing.JButton();
        changepassword1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        transaction = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        report = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mbg.setBackground(new java.awt.Color(204, 255, 255));
        mbg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(153, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profilepic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jPanel5.add(profilepic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        cnum.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cnum.setText("Contactnum:");
        jPanel5.add(cnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 200, 20));

        role.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        role.setText("Role:");
        jPanel5.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 200, 20));

        email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        email.setText("Email:");
        jPanel5.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 200, 20));

        name.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        name.setText("Name:");
        jPanel5.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 20));

        changeProfileButton.setText("Change Profile Picture");
        changeProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeProfileButtonActionPerformed(evt);
            }
        });
        jPanel5.add(changeProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        changepassword1.setText("Change Password");
        changepassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepassword1ActionPerformed(evt);
            }
        });
        jPanel5.add(changepassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 20));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 510));

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/motorbike.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 260, 180));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Motorcycle System Management ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 350, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 370, 510));

        mbg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 700, 510));

        transaction.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        transaction.setText("TRANSACTION");
        transaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionMouseClicked(evt);
            }
        });
        mbg.add(transaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        dashboard.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        dashboard.setText("DASHBOARD");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        mbg.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setText("PROFILE");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        mbg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 30));

        report.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        report.setText("REPORT");
        report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportMouseClicked(evt);
            }
        });
        mbg.add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        jLabel9.setText("Logout");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jLabel9FocusLost(evt);
            }
        });
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        mbg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        getContentPane().add(mbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void changeProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeProfileButtonActionPerformed
         JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Select Profile Picture");
    fileChooser.setAcceptAllFileFilterUsed(false);
    fileChooser.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg", "gif"));

    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        try {
            // Create folder if it doesn't exist
            File directory = new File("profilepics");
            directory.mkdirs();

            // Copy selected image to profilepics folder with user ID as filename
            File destFile = new File("profilepics/user_" + session.getU_id() + ".png");
            Files.copy(selectedFile.toPath(), destFile.toPath(), StandardCopyOption.REPLACE_EXISTING);

            // Load and show image in JLabel
            Image img = ImageIO.read(destFile);
            img = img.getScaledInstance(profilepic.getWidth(), profilepic.getHeight(), Image.SCALE_SMOOTH);
            profilepic.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to load or save image.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

        
        
    }//GEN-LAST:event_changeProfileButtonActionPerformed

    private void changepassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepassword1ActionPerformed
        changepassword acc = new changepassword(
        session.getU_id(), 
        session.getFirstName(), 
        session.getLastName(), 
        session.getEmail(), 
        session.getContact()
    );
        acc.setVisible(true);
        
    }//GEN-LAST:event_changepassword1ActionPerformed

    private void transactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionMouseClicked

        Motorcycle cycle = new Motorcycle();
        cycle.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transactionMouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        UserDB db = new UserDB();

        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        account acc = new account();

        acc.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseClicked
        employeereport rep = new employeereport();
        rep.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportMouseClicked

    private void jLabel9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel9FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9FocusLost

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        login log = new login();

        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeProfileButton;
    private javax.swing.JButton changepassword1;
    private javax.swing.JLabel cnum;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel mbg;
    private javax.swing.JLabel name;
    private javax.swing.JLabel profilepic;
    private javax.swing.JLabel report;
    private javax.swing.JLabel role;
    private javax.swing.JLabel transaction;
    // End of variables declaration//GEN-END:variables
}
