/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import admin.*;
import config.connectDB;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vienz
 */
public class employeereport extends javax.swing.JFrame {

    /**
     * Creates new form adminreport
     */
    public employeereport() {
        initComponents();
        loadTransactionLogs();
    }
    
    public void loadTransactionLogs() {
    // Define column headers (including Status)
    String[] columnNames = {
        "Transaction ID",
        "First Name",
        "Last Name",
        "Email",
        "Motorcycle Type",
        "Contact Number",
        "Creation Date",
        "Status" // <-- Include Status column
    };

    // Create a new table model with the headers
    DefaultTableModel model = new DefaultTableModel(columnNames, 0);
    overview.setModel(model); // Set the model to the table

    try {
        // Establish database connection
        Connection conn = connectDB.getConnection();

        // SQL query to select only APPROVED transactions and include status
        String sql = "SELECT t_id, t_firstname, t_lastname, t_email, t_mtype, t_contactnumber, t_creationdate, status "
                   + "FROM tbl_transaction WHERE status = 'Approve' ORDER BY t_creationdate DESC";
        PreparedStatement stmt = conn.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery();

        // Loop through the result set and add data to the table
        while (rs.next()) {
            int transactionId = rs.getInt("t_id");
            String firstName = rs.getString("t_firstname");
            String lastName = rs.getString("t_lastname");
            String email = rs.getString("t_email");
            String motorcycleType = rs.getString("t_mtype");
            String contactNumber = rs.getString("t_contactnumber");
            String creationDate = rs.getString("t_creationdate");
            String status = rs.getString("status");

            // Add row data to the table model
            model.addRow(new Object[]{
                transactionId,
                firstName,
                lastName,
                email,
                motorcycleType,
                contactNumber,
                creationDate,
                status
            });
        }

        // Close resources
        rs.close();
        stmt.close();
        conn.close();
    } catch (SQLException e) {
        e.printStackTrace();
        System.out.println("Error loading transaction logs: " + e.getMessage());
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        overview = new javax.swing.JTable();
        refresh = new javax.swing.JButton();
        reservation = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        transaction = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        report = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mbg.setBackground(new java.awt.Color(204, 255, 255));
        mbg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(153, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        overview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Email", "Action", "Log Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(overview);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 660, 280));

        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel5.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        reservation.setText("GET REPORT");
        reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationActionPerformed(evt);
            }
        });
        jPanel5.add(reservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, -1, -1));

        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel5.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 690, 430));

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MOTORCYCLE SYSTEM MANAGEMENT");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 400, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 80));

        mbg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 690, 510));

        transaction.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        transaction.setText("TRANSACTION");
        transaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionMouseClicked(evt);
            }
        });
        mbg.add(transaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        dashboard.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        dashboard.setText("DASHBOARD");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        mbg.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setText("PROFILE");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        mbg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 30));

        report.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        report.setText("REPORT");
        report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportMouseClicked(evt);
            }
        });
        mbg.add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        loadTransactionLogs();
    }//GEN-LAST:event_refreshActionPerformed

    private void reservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationActionPerformed

        int selectedRow = overview.getSelectedRow();

if (selectedRow == -1) {
    JOptionPane.showMessageDialog(null, "Please select a transaction from the table first.");
    return;
}

// Extract values from the visible columns in tbl_transaction
String firstName = overview.getValueAt(selectedRow, 1).toString();  // t_firstname
String lastName = overview.getValueAt(selectedRow, 2).toString();   // t_lastname
String email = overview.getValueAt(selectedRow, 3).toString();      // t_email
String motorcycleType = overview.getValueAt(selectedRow, 4).toString(); // t_mtype
String contactNumber = overview.getValueAt(selectedRow, 5).toString(); // t_contactnumber
String id = overview.getValueAt(selectedRow, 0).toString();          // t_id

// Fetch t_creationdate and t_status from the database
try {
    connectDB dbc = new connectDB();
    String query = "SELECT t_creationdate, status FROM tbl_transaction WHERE t_id = ?";
    PreparedStatement pst = dbc.getConnection().prepareStatement(query);
    pst.setString(1, id);
    ResultSet rs = pst.executeQuery();

    if (rs.next()) {
        String creationDate = rs.getString("t_creationdate");
        String status = rs.getString("status");

        // Format and show details in a dialog
        StringBuilder details = new StringBuilder();
        details.append("First Name: ").append(firstName).append("\n");
        details.append("Last Name: ").append(lastName).append("\n");
        details.append("Email: ").append(email).append("\n");
        details.append("Motorcycle Type: ").append(motorcycleType).append("\n");
        details.append("Contact Number: ").append(contactNumber).append("\n");
        details.append("Creation Date: ").append(creationDate).append("\n");
        details.append("Status: ").append(status).append("\n");

        // Show the details in a JOptionPane dialog
        JOptionPane.showMessageDialog(null, details.toString(), "Transaction Details", JOptionPane.INFORMATION_MESSAGE);
    }

} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Error loading additional data: " + e.getMessage());
}



    }//GEN-LAST:event_reservationActionPerformed

    private void transactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionMouseClicked

        Motorcycle cycle = new Motorcycle();
        cycle.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transactionMouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        adminDB db = new adminDB();

        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        account acc = new account();

        acc.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseClicked
        adminreport rep = new adminreport();
        rep.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportMouseClicked

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        int selectedRow = overview.getSelectedRow();

    // If no row is selected, show a message and exit
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a reservation to print.");
        return;
    }

    // Assuming the reservationId is in the first column (index 0)
    int reservationId = Integer.parseInt(overview.getValueAt(selectedRow, 0).toString());

    // Call the print receipt method and pass the reservationId
    printReceipt(reservationId);
    }//GEN-LAST:event_printActionPerformed
    
    private void printReceipt(int transactionId) {
    // Create a PrinterJob instance
    PrinterJob printerJob = PrinterJob.getPrinterJob();

    printerJob.setPrintable((Graphics g, PageFormat pf, int pageIndex) -> {
        if (pageIndex > 0) {
            return Printable.NO_SUCH_PAGE;
        }

        // Title Section
        g.setFont(new Font("SansSerif", Font.BOLD, 16));
        g.setColor(Color.BLACK);
        g.drawString("Motorcycle System Management", 150, 70);
        g.drawLine(100, 80, 500, 80);

        // Font for content
        g.setFont(new Font("Monospaced", Font.PLAIN, 12));

        try (Connection conn = connectDB.getConnection()) {
            String sql = "SELECT * FROM tbl_transaction WHERE t_id = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1, transactionId);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                String firstName = rs.getString("t_firstname");
                String lastName = rs.getString("t_lastname");
                String email = rs.getString("t_email");
                String contactNumber = rs.getString("t_contactnumber");
                String mtype = rs.getString("t_mtype");
                String creationDate = rs.getString("t_creationdate");
                String status = rs.getString("status");

                int y = 100;

                // Customer Info Section
                g.setFont(new Font("SansSerif", Font.BOLD, 12));
                g.drawString("Customer Information", 100, y);
                g.setFont(new Font("Monospaced", Font.PLAIN, 12));
                y += 15;
                g.drawString("Name           : " + firstName + " " + lastName, 100, y);
                y += 15;
                g.drawString("Email          : " + email, 100, y);
                y += 15;
                g.drawString("Contact Number : " + contactNumber, 100, y);

                y += 25; // Add space before next section

                // Transaction Details Section
                g.setFont(new Font("SansSerif", Font.BOLD, 12));
                g.drawString("Transaction Details", 100, y);
                g.setFont(new Font("Monospaced", Font.PLAIN, 12));
                y += 15;
                g.drawString("Transaction ID : " + transactionId, 100, y);
                y += 15;
                g.drawString("Motorcycle Type: " + mtype, 100, y);
                y += 15;
                g.drawString("Creation Date  : " + creationDate, 100, y);
                y += 15;
                g.drawString("Status         : " + status, 100, y);

                // Footer
                y += 30;
                g.setFont(new Font("SansSerif", Font.ITALIC, 10));
                g.drawString("Thank you for using Motorcycle System Management!", 100, y);
                g.drawLine(100, y + 5, 500, y + 5);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return Printable.PAGE_EXISTS;
    });

    // Trigger the print dialog
    boolean doPrint = printerJob.printDialog();
    if (doPrint) {
        try {
            printerJob.print();
        } catch (PrinterException e) {
            e.printStackTrace();
        }
    }




    // Display the print dialog to allow user to choose a printer
    if (printerJob.printDialog()) {
        try {
            printerJob.print();  // Print the document
        } catch (PrinterException e) {
            e.printStackTrace();
        }
    }
}
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeereport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mbg;
    private javax.swing.JTable overview;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JLabel report;
    private javax.swing.JButton reservation;
    private javax.swing.JLabel transaction;
    // End of variables declaration//GEN-END:variables
}
