/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import admin.adminDB;
import config.DBLogger;
import config.connectDB;
import config.hasher;
import config.session;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author vienz
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }
    
    
    
    public String[] loginAcc(String email, String password) {
    connectDB con = new connectDB();

    try {
        String query = "SELECT u_hashpw, u_type, u_status FROM tbl_user WHERE u_email = ?";
        PreparedStatement pstmt = con.getConnection().prepareStatement(query);
        pstmt.setString(1, email.trim());
        ResultSet resultSet = pstmt.executeQuery();

        if (resultSet.next()) {
            String storedHashedPassword = resultSet.getString("u_hashpw");
            String hashedInputPassword = hasher.hashPassword(password); // Hash input password

            // Compare hashed input with stored hash
            if (hashedInputPassword.equals(storedHashedPassword)) {
                return new String[]{resultSet.getString("u_type").trim(), resultSet.getString("u_status").trim()};
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    return null; // Return null if login fails
}


    
    public String[] getUserDetails(String email) {
    connectDB con = new connectDB();
    try {
        String query = "SELECT u_id, u_firstname, u_lastname, u_email, u_contactnumber, u_type, u_status FROM tbl_user WHERE u_email = ?";
        PreparedStatement pstmt = con.getConnection().prepareStatement(query);
        pstmt.setString(1, email.trim()); // Set email as the query parameter
        ResultSet resultSet = pstmt.executeQuery();

        if (resultSet.next()) {
            return new String[]{
                resultSet.getString("u_id").trim(),
                resultSet.getString("u_firstname").trim(),
                resultSet.getString("u_lastname").trim(),
                resultSet.getString("u_email").trim(),
                resultSet.getString("u_contactnumber").trim(),
                resultSet.getString("u_type").trim(),
                resultSet.getString("u_status").trim()
            };
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    return null; // Return null if no user is found
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        logintext = new javax.swing.JLabel();
        registerbutton = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();
        forgotpassword = new javax.swing.JLabel();
        emailtext = new javax.swing.JLabel();
        passtext = new javax.swing.JLabel();
        requireduser = new javax.swing.JLabel();
        requiredpass = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 123, 240, 36));

        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 213, 240, 36));

        logintext.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        logintext.setText("Login");
        jPanel2.add(logintext, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 33, -1, -1));

        registerbutton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        registerbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerbutton.setText("Don't have an account? Click here to Register");
        registerbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerbuttonMouseClicked(evt);
            }
        });
        jPanel2.add(registerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 320, -1));

        loginbutton.setBackground(new java.awt.Color(241, 185, 185));
        loginbutton.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        loginbutton.setText("Login");
        loginbutton.setBorderPainted(false);
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 295, 240, -1));

        forgotpassword.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        forgotpassword.setText("Forgot password");
        forgotpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotpasswordMouseClicked(evt);
            }
        });
        jPanel2.add(forgotpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 120, -1));

        emailtext.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        emailtext.setText("Email");
        jPanel2.add(emailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        passtext.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        passtext.setText("Password");
        jPanel2.add(passtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 193, -1, -1));
        jPanel2.add(requireduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 165, 225, 10));
        jPanel2.add(requiredpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 255, 240, 13));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 54, 350, 390));

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/motorbike 2.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 300, 280));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Motorcycle System Management");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 300, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 360, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        Font smallFont = new Font("Arial", Font.PLAIN, 10); 
username.setFont(smallFont); 
requireduser.setFont(smallFont); 

String user = username.getText();

if (user.isEmpty()) {
    username.setForeground(Color.RED);
    requireduser.setText("Username is required");
    requireduser.setForeground(Color.RED);
} else {
    username.setForeground(Color.BLACK);
    requireduser.setText("");
}

username.repaint();
    }//GEN-LAST:event_usernameFocusLost

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
Font smallFont = new Font("Arial", Font.PLAIN, 10);
password.setFont(smallFont); 
requiredpass.setFont(smallFont); 

String user = password.getText();

if (user.isEmpty()) {
    password.setForeground(Color.RED);
    requiredpass.setText("Password is required");
    requiredpass.setForeground(Color.RED);
} else {
    username.setForeground(Color.BLACK);
    requiredpass.setText("");
}

password.repaint();
    }//GEN-LAST:event_passwordFocusLost

    private void registerbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbuttonMouseClicked
        register reg = new register();

        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerbuttonMouseClicked

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        String user = username.getText().trim();
    String pass = password.getText().trim();

    if (user.isEmpty() || pass.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username and/or password cannot be empty.", "Login Error", JOptionPane.ERROR_MESSAGE);
        username.requestFocus();
        return;
    }

    try {
        // Directly use the entered username and password without hashing
        String[] loginData = loginAcc(user, pass);

        if (loginData == null) {
            // Failed login attempt
            DBLogger.log(user, "Failed login attempt");  // Log failed attempt
            JOptionPane.showMessageDialog(this, "Incorrect username or password.", "Login Error", JOptionPane.ERROR_MESSAGE);
            password.requestFocus();
            return;
        }

        String[] userDetails = getUserDetails(user);

        String userID = userDetails[0];
        String firstName = userDetails[1];
        String lastName = userDetails[2];
        String email = userDetails[3];
        String contactNumber = userDetails[4];
        String accType = loginData[0];
        String accStatus = loginData[1];

        if (!"active".equalsIgnoreCase(accStatus)) {
            // Account is not active
            DBLogger.log(user, "Inactive account login attempt");  // Log attempt with inactive account
            JOptionPane.showMessageDialog(this, "Your account is still pending. Please contact the administrator.", "Login Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        session sess = session.getInstance();
        sess.setU_id(userID);
        sess.setUsername(user);
        sess.setFirstName(firstName);
        sess.setLastName(lastName);
        sess.setEmail(email);
        sess.setContact(contactNumber);
        sess.setAcc_type(accType);
        sess.setAcc_status(accStatus);

        if (accType != null) {
            if ("Admin".equalsIgnoreCase(accType)) {
                DBLogger.log(user, "Admin logged in");  // Log successful login for Admin
                new adminDB().setVisible(true);
            } else if ("Employee".equalsIgnoreCase(accType)) {
                DBLogger.log(user, "Employee logged in");  // Log successful login for Employee
                new UserDB().setVisible(true);
            } else {
                // Invalid user type
                DBLogger.log(user, "Unknown user type login attempt");  // Log unknown user type attempt
                JOptionPane.showMessageDialog(this, "Unknown user type!", "Login Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            this.dispose(); // Close login window
        } else {
            // Invalid login credentials
            DBLogger.log(user, "Incorrect login credentials");  // Log incorrect credentials attempt
            JOptionPane.showMessageDialog(this, "Incorrect username or password.", "Login Error", JOptionPane.ERROR_MESSAGE);
            password.requestFocus();
        }

    } catch (Exception e) {
        // Log error during login
        DBLogger.log(user, "Error during login: " + e.getMessage());  // Log error
        JOptionPane.showMessageDialog(this, "Error during login: " + e.getMessage(), "Login Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }


    }//GEN-LAST:event_loginbuttonActionPerformed

    private void forgotpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpasswordMouseClicked
        forgotpassword forgot = new forgotpassword();
        forgot.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_forgotpasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailtext;
    private javax.swing.JLabel forgotpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel logintext;
    private javax.swing.JLabel passtext;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel registerbutton;
    private javax.swing.JLabel requiredpass;
    private javax.swing.JLabel requireduser;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
