/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import crud.*;
import admin.accountmanager;
import config.connectDB;
import config.hasher;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import panel.login;

/**
 *
 * @author vienz
 */
public class Transaction extends javax.swing.JFrame {

    /**
     * Creates new form addaccount
     */
    public Transaction() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterError = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        RegisterSuccess = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        firstname = new javax.swing.JTextField();
        logintext = new javax.swing.JLabel();
        purchase = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        requiredfname = new javax.swing.JLabel();
        lastnametext = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        requiredlname = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        emailtext = new javax.swing.JLabel();
        requiredemail = new javax.swing.JLabel();
        contactnumber = new javax.swing.JTextField();
        cnumbertext = new javax.swing.JLabel();
        requiredcnumber = new javax.swing.JLabel();
        errorType = new javax.swing.JLabel();
        backlogin = new javax.swing.JLabel();
        motorcycletype = new javax.swing.JComboBox<>();
        motorcyclebrand = new javax.swing.JLabel();
        requiredtype = new javax.swing.JLabel();

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 100, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Sign-up failed! Please complete all fields correctly.        ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 490, 40));

        javax.swing.GroupLayout RegisterErrorLayout = new javax.swing.GroupLayout(RegisterError.getContentPane());
        RegisterError.getContentPane().setLayout(RegisterErrorLayout);
        RegisterErrorLayout.setHorizontalGroup(
            RegisterErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        RegisterErrorLayout.setVerticalGroup(
            RegisterErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 100, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Sign-up successful!");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 180, 40));

        javax.swing.GroupLayout RegisterSuccessLayout = new javax.swing.GroupLayout(RegisterSuccess.getContentPane());
        RegisterSuccess.getContentPane().setLayout(RegisterSuccessLayout);
        RegisterSuccessLayout.setHorizontalGroup(
            RegisterSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        RegisterSuccessLayout.setVerticalGroup(
            RegisterSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameFocusLost(evt);
            }
        });
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        jPanel2.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 196, 30));

        logintext.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        logintext.setText("MAKE A TRANSACTION");
        jPanel2.add(logintext, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        purchase.setBackground(new java.awt.Color(241, 185, 185));
        purchase.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        purchase.setText("PURCHASE");
        purchase.setBorderPainted(false);
        purchase.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                purchaseFocusLost(evt);
            }
        });
        purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseActionPerformed(evt);
            }
        });
        jPanel2.add(purchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 170, 40));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("First Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        requiredfname.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jPanel2.add(requiredfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 180, 10));

        lastnametext.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lastnametext.setText("Last Name");
        jPanel2.add(lastnametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        lastname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnameFocusLost(evt);
            }
        });
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        jPanel2.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 196, 30));

        requiredlname.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jPanel2.add(requiredlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 190, 10));

        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 196, 30));

        emailtext.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        emailtext.setText("Email");
        jPanel2.add(emailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 54, -1));

        requiredemail.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jPanel2.add(requiredemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 182, 190, 10));

        contactnumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contactnumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactnumberFocusLost(evt);
            }
        });
        contactnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnumberActionPerformed(evt);
            }
        });
        jPanel2.add(contactnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 197, 30));

        cnumbertext.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cnumbertext.setText("Contact Number");
        jPanel2.add(cnumbertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        requiredcnumber.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jPanel2.add(requiredcnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 190, 10));

        errorType.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jPanel2.add(errorType, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 190, 10));

        backlogin.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        backlogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backlogin.setText("Click here to go back");
        backlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backloginMouseClicked(evt);
            }
        });
        jPanel2.add(backlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 170, 50));

        motorcycletype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Choose You Want to Buy)", "BMW R Nine T", "Ducati Pagnigale V2", "Yamaha MT-27", "" }));
        motorcycletype.setOpaque(false);
        motorcycletype.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                motorcycletypeFocusLost(evt);
            }
        });
        motorcycletype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorcycletypeActionPerformed(evt);
            }
        });
        jPanel2.add(motorcycletype, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 200, 40));

        motorcyclebrand.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        motorcyclebrand.setText("MOTORCYCLE BRAND");
        jPanel2.add(motorcyclebrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        requiredtype.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jPanel2.add(requiredtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 190, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 570, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusLost
        Font smallFont = new Font("Arial", Font.PLAIN, 10);
        firstname.setFont(smallFont);
        requiredfname.setFont(smallFont);

        String user = firstname.getText();

        if (user.isEmpty()) {
            firstname.setForeground(Color.RED);
            requiredfname.setText("First Name is required");
            requiredfname.setForeground(Color.RED);
        } else {
            firstname.setForeground(Color.BLACK);
            requiredfname.setText("");
        }

        firstname.repaint();
    }//GEN-LAST:event_firstnameFocusLost

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void purchaseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_purchaseFocusLost

    }//GEN-LAST:event_purchaseFocusLost

    private void purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseActionPerformed
// Get the first name, last name, email, motorcycle type, and contact number
String firstName = firstname.getText();
String lastName = lastname.getText();
String emailAddress = email.getText();  // Get the email address
String motorcycleType = (String) motorcycletype.getSelectedItem();  // Get the selected motorcycle type
String contactNumber = contactnumber.getText();

// Check for any missing required fields
if (firstName.isEmpty() || lastName.isEmpty() || emailAddress.isEmpty() || motorcycleType.equals("(Choose Motorcycle Type)") || contactNumber.isEmpty()) {
    // Show a message or highlight the fields that are missing
    if (firstName.isEmpty()) {
        requiredfname.setText("First Name is required");
    }
    if (lastName.isEmpty()) {
        requiredlname.setText("Last Name is required");
    }
    if (emailAddress.isEmpty()) {
        requiredemail.setText("Email is required");
    }
    if (motorcycleType.equals("(Choose Motorcycle Type)")) {
        requiredtype.setText("Motorcycle Type is required");
    }
    if (contactNumber.isEmpty()) {
        requiredcnumber.setText("Contact number is required");
    }
} else {
    // Insert transaction into the database if everything is valid
    try {
        // Establish database connection
        connectDB db = new connectDB();
        Connection conn = db.getConnection();

        // SQL query to insert transaction details into tbl_transaction including status as 'Pending'
        String query = "INSERT INTO tbl_transaction (t_firstname, t_lastname, t_email, t_mtype, t_contactnumber, t_creationdate, status) "
                     + "VALUES (?, ?, ?, ?, ?, NOW(), ?)";

        // Create prepared statement with RETURN_GENERATED_KEYS option
        PreparedStatement stmt = conn.prepareStatement(query, PreparedStatement.RETURN_GENERATED_KEYS);
        stmt.setString(1, firstName);
        stmt.setString(2, lastName);
        stmt.setString(3, emailAddress);
        stmt.setString(4, motorcycleType);
        stmt.setString(5, contactNumber);
        stmt.setString(6, "Pending"); // Set status to "Pending"

        // Execute the insert and retrieve generated keys
        int result = stmt.executeUpdate();
        if (result > 0) {
            // Get generated transaction ID
            java.sql.ResultSet rs = stmt.getGeneratedKeys();
            if (rs.next()) {
                int transactionId = rs.getInt(1);  // Transaction ID
                System.out.println("Transaction created successfully! ID: " + transactionId);
            }

            // Optionally, clear the fields after submission
            firstname.setText("");
            lastname.setText("");
            email.setText("");
            motorcycletype.setSelectedIndex(0);
            contactnumber.setText("");
        }

        // After successful submission, navigate back to the transaction panel
        this.dispose();  // Close the current window
        adminDB transaction = new adminDB();  // Create a new instance of the transaction panel
        transaction.setVisible(true);  // Show the transaction panel
    } catch (Exception e) {
        e.printStackTrace();
        System.out.println("Error inserting transaction: " + e.getMessage());
    }
}


    }//GEN-LAST:event_purchaseActionPerformed

    private void lastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusLost
        Font smallFont = new Font("Arial", Font.PLAIN, 10);
        lastname.setFont(smallFont);
        requiredlname.setFont(smallFont);

        String user = lastname.getText();

        if (user.isEmpty()) {
            lastname.setForeground(Color.RED);
            requiredlname.setText("Last Name is required");
            requiredlname.setForeground(Color.RED);
        } else {
            lastname.setForeground(Color.BLACK);
            requiredlname.setText("");
        }

        lastname.repaint();
    }//GEN-LAST:event_lastnameFocusLost

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        
    }//GEN-LAST:event_emailFocusLost

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed

    }//GEN-LAST:event_emailActionPerformed

    private void contactnumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactnumberFocusLost
        Font smallFont = new Font("Arial", Font.PLAIN, 10);
        contactnumber.setFont(smallFont);
        requiredcnumber.setFont(smallFont);

        String user = contactnumber.getText();

        if (user.isEmpty()) {
            contactnumber.setForeground(Color.RED);
            requiredcnumber.setText("Contact Number is required");
            requiredcnumber.setForeground(Color.RED);
        } else if (!user.matches("\\d{11}")) {
            contactnumber.setForeground(Color.RED);
            requiredcnumber.setText("Contact Number must be exactly 11 digits");
            requiredcnumber.setForeground(Color.RED);
        } else {
            contactnumber.setForeground(Color.BLACK);
            requiredcnumber.setText("");
        }

        contactnumber.repaint();
    }//GEN-LAST:event_contactnumberFocusLost

    private void contactnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnumberActionPerformed

    private void backloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backloginMouseClicked
        login log = new login();

        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backloginMouseClicked

    private void motorcycletypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_motorcycletypeFocusLost
        if (motorcycletype.getSelectedIndex() == 0) {
            motorcycletype.setForeground(Color.RED);
            requiredtype.setText("Please choose account type");
            requiredtype.setForeground(Color.RED);
        } else {
            motorcycletype.setForeground(Color.BLACK);
            requiredtype.setText("");
        }

        motorcycletype.repaint();
    }//GEN-LAST:event_motorcycletypeFocusLost

    private void motorcycletypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorcycletypeActionPerformed

    }//GEN-LAST:event_motorcycletypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RegisterError.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private boolean signUpValidation() {
    boolean valid = true;

    // First Name Validation
    String user = firstname.getText();
    if (user.isEmpty()) {
        firstname.setForeground(Color.RED);
        requiredfname.setText("First Name is required");
        requiredfname.setForeground(Color.RED);
        valid = false;
    } else {
        firstname.setForeground(Color.BLACK);
        requiredfname.setText("");
    }
    firstname.repaint();

    // Last Name Validation
    String last = lastname.getText();
    if (last.isEmpty()) {
        lastname.setForeground(Color.RED);
        requiredlname.setText("Last Name is required");
        requiredlname.setForeground(Color.RED);
        valid = false;
    } else {
        lastname.setForeground(Color.BLACK);
        requiredlname.setText("");
    }
    lastname.repaint();

    

    // Contact Number Validation
    String con = contactnumber.getText();
    if (con.isEmpty()) {
        contactnumber.setForeground(Color.RED);
        requiredcnumber.setText("Contact Number is required");
        requiredcnumber.setForeground(Color.RED);
        valid = false;
    } else if (!con.matches("\\d{11}")) {  // Ensure 11 digits
        contactnumber.setForeground(Color.RED);
        requiredcnumber.setText("Contact Number must be exactly 11 digits");
        requiredcnumber.setForeground(Color.RED);
        valid = false;
    } else {
        contactnumber.setForeground(Color.BLACK);
        requiredcnumber.setText("");
    }
    contactnumber.repaint();

    return valid;
}
    
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog RegisterError;
    private javax.swing.JDialog RegisterSuccess;
    private javax.swing.JLabel backlogin;
    private javax.swing.JLabel cnumbertext;
    private javax.swing.JTextField contactnumber;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailtext;
    private javax.swing.JLabel errorType;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField lastname;
    private javax.swing.JLabel lastnametext;
    private javax.swing.JLabel logintext;
    private javax.swing.JLabel motorcyclebrand;
    private javax.swing.JComboBox<String> motorcycletype;
    private javax.swing.JButton purchase;
    private javax.swing.JLabel requiredcnumber;
    private javax.swing.JLabel requiredemail;
    private javax.swing.JLabel requiredfname;
    private javax.swing.JLabel requiredlname;
    private javax.swing.JLabel requiredtype;
    // End of variables declaration//GEN-END:variables
}
